geocoder.photon.base-url=https://photon.komoot.io
geocoder.photon.endpoints.search=/api
geocoder.photon.endpoints.reverse=/reverse
geocoder.photon.user-agent=geo-api/1.0 (laboratorio2026)

geocoder.nominatim.base-url=https://nominatim.openstreetmap.org
geocoder.nominatim.endpoints.search=/search
geocoder.nominatim.endpoints.reverse=/reverse
geocoder.nominatim.user-agent=geo-api/1.0 (laboratorio2026)
geocoder.nominatim.min-interval-ms=1100

geocoder.sudir.base-url=https://direcciones.ide.uy
geocoder.sudir.endpoints.search=/api/v0/geocode/BusquedaDireccion
geocoder.sudir.endpoints.reverse=/api/v1/geocode/reverse
geocoder.sudir.user-agent=geo-api/1.0 (laboratorio2026)